### ISSUE TITLE
NPM package includes a Yarn error log

### ISSUE THREAD

**Issue by AustinLeeGordon** [Qix-/node-is-arrayish#6]
A 51 KB yarn-error.log file is being shipped with v0.3.2. Here's a screenshot after doing a fresh install.

![image](https://user-images.githubusercontent.com/19353967/47797230-ef044c00-dcf3-11e8-8b33-2c381a296ff4.png)

**Comment by Qix-** [comment]
Yep they silently introduced this file which got it included in a bunch of places lol.

**Comment by Qix-** [comment]
Fixed by #7

**Comment by ffxsam** [comment]
@Qix- Almost fixed! It still needs to be re-published to the npm registry. I just did a fresh install and I still see it.

```
-rw-r--r--  1 samh  staff    50K Mar 14 19:20 node_modules/is-arrayish/yarn-error.log
```
